### ISSUE TITLE
AR9656 not working

### ISSUE THREAD

**Issue by dedicahyadi** [IlhamSevensky/ASUS-X556UQ-HACKINTOSH-OPENCORE#2]
Currently my os is Big Sur and im using OC 0.6.4 with ar9565, i've followed that tutorial from insanelymac (HS80211Family.kext Modif). Still didn't work, can you help me to making this wifi chipset working properly on my laptop (Asus X466URK Core i5 7th Gen)?

**Comment by IlhamSevensky** [comment]
Unfortunately I haven't tried it on Mac OS Big Sur beta or its stable version because this laptop is my main device for work and now I'm not using AR9565, I've replaced it with BCM94360NG.
I will update this repository when I update to the mac os big sur

**Comment by samokisha** [comment]
Have you already tried using AR9565 on your laptop with Mac OS Big Sur? Is it working?

**Comment by IlhamSevensky** [comment]
> Have you already tried using AR9565 on your laptop with Mac OS Big Sur? Is it working?

I haven't tried it yet, I've changed my network card
