### ISSUE TITLE
Doesn't load into installer.

### ISSUE THREAD

**Issue by the80hz** [IlhamSevensky/ASUS-X556UQ-HACKINTOSH-OPENCORE#3]
Hi, I have the same laptop as yours. Differ only:
- CPU (core i3)
- RAM (8gb 2133mhz)
- Wifi (ar9565)
- Touchpad (FTE 1001)
- SSD (sata 128gb).

Before using your EFI, I corrected the config.plist and replaced the VoodooI2CELAN to VoodooI2CFTE. I didn't touch anything else.
When I boot into the macOS Catalina (10.15.5) Installer, I get a cursor near the apple, but then immediately the laptop turns off. The only thing I see at the end of the log is CPU halted.

As for Big Sur (11.2), I have kernel panic while loading.
I have no idea at all why this is happening.

**Comment by firmanjml** [comment]
@the80hz Have you patch the ssdt correctly?
I used to get panic before when moving the cursor or having usb plugged in but got it to work after patching the right ssdt.

As for Big sur, are you having multiple VoodooInput in the config.plist? if so, you could try disable one of them.
I just got big sur working today by doing that.

**Comment by the80hz** [comment]
@firmanjml I used SSDT which were in EFI. I know how to patch DSDT for Clover, but I can't create SSDT for OpenCore. What about VoodooInput, I only have it in VoodooI2С.

**Comment by the80hz** [comment]
I just found out that the problem is exactly NOT in VoodooI2C, before turning off the laptop, when the cursor appears, I have time to move the cursor. I'll try to throw SSDT one by one, maybe the problem is in them.

upd.
Most likely config.plist doesn't work for my laptop. I have already tried to boot into macOS Mojave, but to no avail, the laptop goes into shutdown.

upd.2 
I wrote my own config.plist but no difference.

**Comment by the80hz** [comment]
![EEE06B2F-59B8-423B-A18B-4D8FBF65762E](https://user-images.githubusercontent.com/64586195/107157669-bce7f700-699e-11eb-8bc5-8f68cac75dc0.jpeg) 
This is what macOS shows on shutdown

**Comment by IlhamSevensky** [comment]
> Hi, I have the same laptop as yours. Differ only:
> 
> * CPU (core i3)
> * RAM (8gb 2133mhz)
> * Wifi (ar9565)
> * Touchpad (FTE 1001)
> * SSD (sata 128gb).
> 
> Before using your EFI, I corrected the config.plist and replaced the VoodooI2CELAN to VoodooI2CFTE. I didn't touch anything else.
> When I boot into the macOS Catalina (10.15.5) Installer, I get a cursor near the apple, but then immediately the laptop turns off. The only thing I see at the end of the log is CPU halted.
> 
> As for Big Sur (11.2), I have kernel panic while loading.
> I have no idea at all why this is happening.

sorry, you have a different cpu type from me too, some of the kext that I use also need patches and custom ssdt (I suggest you read here [here](https://dortania.github.io/OpenCore-Install-Guide/). there is also a way to make a ssdt patch. try it with a minimum kext and minimal patches first then fix other problems one by one.

The kext below is a custom kext, and you also have to adjust some ssdt patches.
- CPUFriend + CPUDataProvider
- USBMap

**Comment by the80hz** [comment]
It turns out that the bios also affects the performance of macOS. It is because of an incorrect copy of the Bios that I did not run Hackintosh. Thank you for the release.
